parameters:
#    banko_compte.example.class: Banko\CompteBundle\Example

services:
#    banko_compte.example:
#        class: %banko_compte.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
